---
- name: download kibana archive
  get_url: >
    url={{ kibana_configs.dl_url }}
    dest={{ kibana_configs.rpm_path }}

- name: install kibana from rpm
  yum: name={{ kibana_configs.rpm_path }}

- name: service start & enabled
  service: name=kibana state=started enabled=yes


